namespace: ernstov
blank-85128:
  defines: runnable
  containers:
    blank-85128:
      build: .
  variables:
    password:
      env: ADMIN_PASSWORD
      type: string
      value: not-set
    user:
      env: ADMIN_USERNAME
      type: string
      value: admin
  services:
    webserver:
      container: blank-85128
      port: 8080
      protocol: tcp
